name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送标签时触发
    branches:
      - main  # 仅在主分支上触发
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write  # 这允许工作流写入仓库内容，包括创建发布

jobs:
  build:
    name: 构建和发布
    runs-on: ubuntu-latest
    environment: dockerhub  # 指定使用dockerhub环境，这样可以访问该环境中的密钥
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 请根据您的项目需求调整Go版本
          
      - name: 获取依赖
        run: go mod download
        
      - name: 安装CGO依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev sqlite3 libsqlite3-dev
          # 安装ARM64交叉编译工具
          sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: 构建
        run: |
            make build-all

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # 在登录到Docker Hub之前添加这个步骤
      - name: 获取版本号
        id: get_version
        run: |
          # 如果是标签推送，直接获取标签版本
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            # 去掉版本号前面的'v'（如果有）
            VERSION=${VERSION#v}
          else
            # 如果不是标签推送，则使用短提交哈希
            VERSION=$(git rev-parse --short HEAD)
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "版本号: $VERSION"

      - name: 登录到Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: 构建并推送多平台Docker镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:latest

      - name: 发布到GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/nilbbs-amd64
            release/nilbbs-arm64
            release/nilbbs.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 上传构建产物（非标签推送）
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: nilbbs-builds
          path: |
            release/nilbbs-amd64
            release/nilbbs-arm64
            release/nilbbs.exe