name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送标签时触发
    branches:
      - main  # 仅在主分支上触发
  workflow_dispatch:  # 允许手动触发工作流

permissions:
  contents: write  # 这允许工作流写入仓库内容，包括创建发布

jobs:
  build:
    name: 构建和发布
    runs-on: ubuntu-latest
    environment: dockerhub  # 指定使用dockerhub环境，这样可以访问该环境中的密钥
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置Go环境
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # 请根据您的项目需求调整Go版本
          
      - name: 获取依赖
        run: go mod download
        
      - name: 安装CGO依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libc6-dev sqlite3 libsqlite3-dev
          # 安装ARM64交叉编译工具
          sudo apt-get install -y gcc-aarch64-linux-gnu
      
      - name: 构建Linux/amd64（启用CGO）
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o nilbbs-linux-amd64 main.go
      
      - name: 构建Linux/arm64（启用CGO）
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=arm64 CC=aarch64-linux-gnu-gcc go build -o nilbbs-linux-arm64 main.go
      
      - name: 构建其他平台（不启用CGO）
        run: |
          CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o nilbbs-macos main.go
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o nilbbs.exe main.go

      - name: 打包发布文件
        run: |
          mkdir -p release
          cp nilbbs-linux-amd64 release/nilbbs-linux
          cp nilbbs-linux-arm64 release/nilbbs-arm64
          cp nilbbs-macos release/
          cp nilbbs.exe release/
          cd release
          tar -czvf nilbbs-linux-amd64.tar.gz nilbbs-linux
          tar -czvf nilbbs-macos-amd64.tar.gz nilbbs-macos
          zip nilbbs-windows-amd64.zip nilbbs.exe
          tar -czvf nilbbs-linux-arm64.tar.gz nilbbs-arm64
          cd ..
          
          # 准备Docker构建所需文件
          # Linux/amd64
          mkdir -p docker-linux-amd64
          cp -r static templates docker-linux-amd64/
          cp nilbbs-linux-amd64 docker-linux-amd64/nilbbs
          
          # Linux/arm64
          mkdir -p docker-linux-arm64
          cp -r static templates docker-linux-arm64/
          cp nilbbs-linux-arm64 docker-linux-arm64/nilbbs
      
      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: 登录到Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: 提取版本信息
        id: get_version
        run: |
          # 如果是标签推送，则使用标签作为版本
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          else
            # 如果是手动触发，使用latest作为版本
            VERSION=latest
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "构建版本: ${VERSION}"
      
      - name: 构建并推送Docker镜像 (AMD64)
        uses: docker/build-push-action@v5
        with:
          context: ./docker-linux-amd64
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:amd64-${{ steps.get_version.outputs.VERSION }}
          file: ./Dockerfile
          
      - name: 构建并推送Docker镜像 (ARM64)
        uses: docker/build-push-action@v5
        with:
          context: ./docker-linux-arm64
          push: true
          platforms: linux/arm64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:arm64-${{ steps.get_version.outputs.VERSION }}
          file: ./Dockerfile
          
      - name: 创建并推送多平台清单
        run: |
          # 确保使用 docker CLI 的实验特性
          export DOCKER_CLI_EXPERIMENTAL=enabled
          
          # 创建并推送多平台清单
          docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:${{ steps.get_version.outputs.VERSION }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:amd64-${{ steps.get_version.outputs.VERSION }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:arm64-${{ steps.get_version.outputs.VERSION }}
          
          # 创建 latest 标签
          docker manifest create ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:amd64-${{ steps.get_version.outputs.VERSION }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:arm64-${{ steps.get_version.outputs.VERSION }}
          
          # 将平台标注添加到清单
          docker manifest annotate ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:${{ steps.get_version.outputs.VERSION }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:amd64-${{ steps.get_version.outputs.VERSION }} --os linux --arch amd64
          
          docker manifest annotate ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:${{ steps.get_version.outputs.VERSION }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:arm64-${{ steps.get_version.outputs.VERSION }} --os linux --arch arm64
          
          docker manifest annotate ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:amd64-${{ steps.get_version.outputs.VERSION }} --os linux --arch amd64
          
          docker manifest annotate ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:latest \
            ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:arm64-${{ steps.get_version.outputs.VERSION }} --os linux --arch arm64
          
          # 推送清单
          docker manifest push ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:${{ steps.get_version.outputs.VERSION }}
          docker manifest push ${{ secrets.DOCKER_HUB_USERNAME }}/nilbbs:latest
      
      - name: 发布到GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            release/nilbbs-linux-amd64.tar.gz
            release/nilbbs-macos-amd64.tar.gz
            release/nilbbs-windows-amd64.zip
            release/nilbbs-linux-arm64.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 上传构建产物（非标签推送）
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: nilbbs-builds
          path: |
            release/nilbbs-linux-amd64.tar.gz
            release/nilbbs-macos-amd64.tar.gz
            release/nilbbs-windows-amd64.zip
            release/nilbbs-linux-arm64.tar.gz